name: acdc_new
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - pip:
    - PyQt5>=5.15.4
    - opencv-python-headless
    - fvcore
    - cloudpickle
    - omegaconf
    - torchvision
  - pyqtgraph
  - pandas
  - pytables
  - tqdm
  - natsort
  - scikit-image=0.18
  - pyglet
  - seaborn
  - numba
  - requests
  - tensorflow<2.6.0
  - pytorch=1.9
  - scikit-learn
  - jupyterlab
  - boto3
